NUM_MEMORY_ENTRIES = 11

INDEX = 0
STATE = 1
ACTION = 2
REWARD = 3
NEXT_STATE = 4
GAMMA = 5
IS_TERMINAL = 6
LOSS = 7
OLD_PRIORITY = 8
PRIORITY = 9
POSITION = 10

ACTION_NAMES = ["noop", "right", "main", "left"]